services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui-container"
    environment:
      SWAGGER_JSON: /openapi.yaml
    ports:
      - "9000:8080"
    volumes:
      - $PWD/server/docs/openapi.yaml:/openapi.yaml
