# Pagination

DEFAULT_ENTRIES_PER_PAGE = 50

# Usuario Model

MAX_USUARIO_NAME_LENGTH = 100
MAX_USUARIO_PASSWORD_LENGTH = 100

# Cliente Model

MAX_CLIENTE_NAME_LENGTH = 120
MAX_CLIENTE_APELIDO_LENGTH = 40

# Obra Model
MAX_COD_OBRA_LENGTH = 20
MAX_QUADRA_LENGTH = 40
MAX_LOTE_LENGTH = 40

# Generic Constants

MAX_LOGRADOURO_LENGTH = 120
MAX_TIPO_LOGO_LENGTH = 20
MAX_BAIRRO_LENGTH = 80
MAX_CIDADE_LENGTH = 40
MAX_COMPLEMENTO_LOGO_LENGTH = 120
MAX_TIPO_LOGO_LENGTH = 20
MAX_EMAIL_LENGTH = 100

# Fixed Size Constants

CPF_LENGTH = 14
CNPJ_LENGTH = 18
UF_LENGTH = 2
CEP_LENGTH = 9
