"""Create Obra, Cliente and Usuario tables.

Revision ID: 3cf800c5c119
Revises: 
Create Date: 2024-10-10 12:06:28.569522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cf800c5c119'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cliente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('apelido', sa.String(length=40), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('tipo_logo', sa.String(length=20), nullable=True),
    sa.Column('logradouro', sa.String(length=120), nullable=True),
    sa.Column('complemento', sa.String(length=120), nullable=True),
    sa.Column('bairro', sa.String(length=80), nullable=True),
    sa.Column('cidade', sa.String(length=40), nullable=True),
    sa.Column('uf', sa.CHAR(length=2), nullable=True),
    sa.Column('cep', sa.CHAR(length=9), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('fone1', sa.Integer(), nullable=True),
    sa.Column('fone2', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Cliente_cep'), 'Cliente', ['cep'], unique=False)
    op.create_index(op.f('ix_Cliente_cnpj'), 'Cliente', ['cnpj'], unique=True)
    op.create_index(op.f('ix_Cliente_cpf'), 'Cliente', ['cpf'], unique=True)
    op.create_index(op.f('ix_Cliente_email'), 'Cliente', ['email'], unique=False)
    op.create_index(op.f('ix_Cliente_logradouro'), 'Cliente', ['logradouro'], unique=False)
    op.create_index(op.f('ix_Cliente_nome'), 'Cliente', ['nome'], unique=True)
    op.create_table('Usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Usuario_email'), 'Usuario', ['email'], unique=True)
    op.create_index(op.f('ix_Usuario_name'), 'Usuario', ['name'], unique=False)
    op.create_table('Obra',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cod_obra', sa.String(length=20), nullable=False),
    sa.Column('num_obra', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('cidade', sa.String(length=40), nullable=False),
    sa.Column('uf', sa.CHAR(length=2), nullable=False),
    sa.Column('tipo_logo', sa.String(length=20), nullable=True),
    sa.Column('logradouro', sa.String(length=120), nullable=False),
    sa.Column('complemento', sa.String(length=120), nullable=True),
    sa.Column('bairro', sa.String(length=80), nullable=False),
    sa.Column('cep', sa.CHAR(length=9), nullable=True),
    sa.Column('lote', sa.String(length=40), nullable=True),
    sa.Column('quadra', sa.String(length=40), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('proprietario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['Cliente.id'], ),
    sa.ForeignKeyConstraint(['proprietario_id'], ['Cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Obra_ano'), 'Obra', ['ano'], unique=False)
    op.create_index(op.f('ix_Obra_bairro'), 'Obra', ['bairro'], unique=False)
    op.create_index(op.f('ix_Obra_cidade'), 'Obra', ['cidade'], unique=False)
    op.create_index(op.f('ix_Obra_cod_obra'), 'Obra', ['cod_obra'], unique=True)
    op.create_index(op.f('ix_Obra_complemento'), 'Obra', ['complemento'], unique=False)
    op.create_index(op.f('ix_Obra_data_fim'), 'Obra', ['data_fim'], unique=False)
    op.create_index(op.f('ix_Obra_data_inicio'), 'Obra', ['data_inicio'], unique=False)
    op.create_index(op.f('ix_Obra_logradouro'), 'Obra', ['logradouro'], unique=False)
    op.create_index(op.f('ix_Obra_num_obra'), 'Obra', ['num_obra'], unique=False)
    op.create_index(op.f('ix_Obra_uf'), 'Obra', ['uf'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Obra_uf'), table_name='Obra')
    op.drop_index(op.f('ix_Obra_num_obra'), table_name='Obra')
    op.drop_index(op.f('ix_Obra_logradouro'), table_name='Obra')
    op.drop_index(op.f('ix_Obra_data_inicio'), table_name='Obra')
    op.drop_index(op.f('ix_Obra_data_fim'), table_name='Obra')
    op.drop_index(op.f('ix_Obra_complemento'), table_name='Obra')
    op.drop_index(op.f('ix_Obra_cod_obra'), table_name='Obra')
    op.drop_index(op.f('ix_Obra_cidade'), table_name='Obra')
    op.drop_index(op.f('ix_Obra_bairro'), table_name='Obra')
    op.drop_index(op.f('ix_Obra_ano'), table_name='Obra')
    op.drop_table('Obra')
    op.drop_index(op.f('ix_Usuario_name'), table_name='Usuario')
    op.drop_index(op.f('ix_Usuario_email'), table_name='Usuario')
    op.drop_table('Usuario')
    op.drop_index(op.f('ix_Cliente_nome'), table_name='Cliente')
    op.drop_index(op.f('ix_Cliente_logradouro'), table_name='Cliente')
    op.drop_index(op.f('ix_Cliente_email'), table_name='Cliente')
    op.drop_index(op.f('ix_Cliente_cpf'), table_name='Cliente')
    op.drop_index(op.f('ix_Cliente_cnpj'), table_name='Cliente')
    op.drop_index(op.f('ix_Cliente_cep'), table_name='Cliente')
    op.drop_table('Cliente')
    # ### end Alembic commands ###
