"""Add Cliente table.

Revision ID: 75aacb3add18
Revises: 94fc1429bd40
Create Date: 2024-09-12 12:12:47.115795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75aacb3add18'
down_revision: Union[str, None] = '94fc1429bd40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cliente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('apelido', sa.String(length=40), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('tipo_logo', sa.String(length=20), nullable=True),
    sa.Column('logradouro', sa.String(length=120), nullable=True),
    sa.Column('complemento', sa.String(length=120), nullable=True),
    sa.Column('bairro', sa.String(length=80), nullable=True),
    sa.Column('cidade', sa.String(length=40), nullable=True),
    sa.Column('uf', sa.CHAR(length=2), nullable=True),
    sa.Column('cep', sa.CHAR(length=9), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('fone1', sa.Integer(), nullable=True),
    sa.Column('fone2', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Cliente_cep'), 'Cliente', ['cep'], unique=False)
    op.create_index(op.f('ix_Cliente_cnpj'), 'Cliente', ['cnpj'], unique=False)
    op.create_index(op.f('ix_Cliente_cpf'), 'Cliente', ['cpf'], unique=False)
    op.create_index(op.f('ix_Cliente_email'), 'Cliente', ['email'], unique=False)
    op.create_index(op.f('ix_Cliente_logradouro'), 'Cliente', ['logradouro'], unique=False)
    op.create_index(op.f('ix_Cliente_nome'), 'Cliente', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Cliente_nome'), table_name='Cliente')
    op.drop_index(op.f('ix_Cliente_logradouro'), table_name='Cliente')
    op.drop_index(op.f('ix_Cliente_email'), table_name='Cliente')
    op.drop_index(op.f('ix_Cliente_cpf'), table_name='Cliente')
    op.drop_index(op.f('ix_Cliente_cnpj'), table_name='Cliente')
    op.drop_index(op.f('ix_Cliente_cep'), table_name='Cliente')
    op.drop_table('Cliente')
    # ### end Alembic commands ###
