"""Make Cliente 'nome', 'cpf' and 'cnpj' unique.

Revision ID: 813a6e1975e5
Revises: 84951d9a9c95
Create Date: 2024-10-02 11:01:17.458279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '813a6e1975e5'
down_revision: Union[str, None] = '84951d9a9c95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Cliente_cnpj', table_name='Cliente')
    op.create_index(op.f('ix_Cliente_cnpj'), 'Cliente', ['cnpj'], unique=True)
    op.drop_index('ix_Cliente_cpf', table_name='Cliente')
    op.create_index(op.f('ix_Cliente_cpf'), 'Cliente', ['cpf'], unique=True)
    op.drop_index('ix_Cliente_nome', table_name='Cliente')
    op.create_index(op.f('ix_Cliente_nome'), 'Cliente', ['nome'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Cliente_nome'), table_name='Cliente')
    op.create_index('ix_Cliente_nome', 'Cliente', ['nome'], unique=False)
    op.drop_index(op.f('ix_Cliente_cpf'), table_name='Cliente')
    op.create_index('ix_Cliente_cpf', 'Cliente', ['cpf'], unique=False)
    op.drop_index(op.f('ix_Cliente_cnpj'), table_name='Cliente')
    op.create_index('ix_Cliente_cnpj', 'Cliente', ['cnpj'], unique=False)
    # ### end Alembic commands ###
