"""Create Sondagem tables.

Revision ID: eb788bbc940d
Revises: 3cf800c5c119
Create Date: 2024-10-16 11:47:29.232016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb788bbc940d'
down_revision: Union[str, None] = '3cf800c5c119'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Sondagem_Percussao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sondagens', sa.Integer(), nullable=False),
    sa.Column('metros', sa.Float(precision=2), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['obra_id'], ['Obra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Sondagem_Rotativa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sondagens', sa.Integer(), nullable=False),
    sa.Column('metros_solo', sa.Float(precision=2), nullable=False),
    sa.Column('metros_rocha', sa.Float(precision=2), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['obra_id'], ['Obra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Sondagem_Trado',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sondagens', sa.Integer(), nullable=False),
    sa.Column('metros', sa.Float(precision=2), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['obra_id'], ['Obra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Sondagem_Trado')
    op.drop_table('Sondagem_Rotativa')
    op.drop_table('Sondagem_Percussao')
    # ### end Alembic commands ###
