"""Turn Obra 'cod_obra' into a unique varchar field.

Revision ID: fd5064ef9124
Revises: 813a6e1975e5
Create Date: 2024-10-02 14:49:48.673019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fd5064ef9124'
down_revision: Union[str, None] = '813a6e1975e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Obra', 'cod_obra',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_index('ix_Obra_cod_obra', table_name='Obra')
    op.create_index(op.f('ix_Obra_cod_obra'), 'Obra', ['cod_obra'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Obra_cod_obra'), table_name='Obra')
    op.create_index('ix_Obra_cod_obra', 'Obra', ['cod_obra'], unique=False)
    op.alter_column('Obra', 'cod_obra',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
